# Generated by Django 4.2 on 2023-04-23 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=100)),
                ('visits', models.IntegerField(default='0')),
                ('likes', models.IntegerField(default='0')),
                ('dislikes', models.IntegerField(default='0')),
                ('date', models.CharField(default=' ', max_length=100)),
                ('thumbnail', models.ImageField(default=None, upload_to='../thumbnail_uploaded')),
                ('video', models.FileField(default=None, upload_to='../videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
