# Generated by Django 4.2 on 2023-04-23 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvideo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newvideo',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnail_uploaded'),
        ),
        migrations.AlterField(
            model_name='newvideo',
            name='video',
            field=models.FileField(default=None, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
